version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 2
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "cropperjs"
        versions: [">1.6.2"]
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
